events {}

http {
    server {
        listen 80;
        server_name mydomain.com;

        location / {
            return 301 http://test.mydomain.com$request_uri;
        }
    }

    server {
        listen 80;
        server_name test.mydomain.com;

        location / {
            return 200 "Welcome to test.mydomain.com\n";
        }
    }

    server {
        listen 80;
        server_name beta.mydomain.com;

        location / {
            return 200 "Welcome to beta.mydomain.com\n";
        }
    }
}
